# Generated by Django 5.0.7 on 2024-08-13 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Entry date')),
                ('app_income', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='App income')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Commission')),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Expenses')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
