# Generated by Django 5.0.7 on 2024-08-30 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rideposts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('car_name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.CharField(max_length=255)),
                ('engine', models.CharField(max_length=255)),
                ('fuel', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('gear_number', models.IntegerField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('seat_number', models.IntegerField(max_length=255)),
                ('door_number', models.IntegerField(blank=True, max_length=255, null=True)),
                ('milleage', models.IntegerField(max_length=255)),
                ('power', models.IntegerField(max_length=255)),
                ('mpg', models.IntegerField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('emission_standard', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.IntegerField(max_length=255)),
                ('price', models.IntegerField(max_length=255)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rideposts.file')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
