# Generated by Django 5.0.7 on 2024-09-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ridecars", "0004_carpost_image_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="carpost",
            name="image_id",
        ),
        migrations.RemoveField(
            model_name="carpost",
            name="image_key",
        ),
    ]
