# Generated by Django 5.0.7 on 2024-10-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ridecars", "0006_remove_carpost_phone_number_carpost_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carpost",
            name="door_number",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carpost",
            name="gear_number",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="carpost",
            name="milleage",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="carpost",
            name="mpg",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carpost",
            name="power",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="carpost",
            name="price",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="carpost",
            name="seat_number",
            field=models.CharField(),
        ),
    ]
