# Generated by Django 5.0.7 on 2024-08-15 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rideauth", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
