# Generated by Django 5.0.7 on 2024-08-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rideauth', '0003_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
